# Checkov configuration file
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Framework to scan
framework:
  - terraform

# Output format
output:
  - cli
  - junitxml

# Directories to scan
directory:
  - terraform/

# Skip specific checks with justification
# Each skip has a documented reason - see docs/07-exceptions-process.md
skip-check:
  # Organization-level checks (not applicable for single account setup)
  - CKV2_AWS_38  # Route 53 DNS query logging - no hosted zones in this baseline
  - CKV2_AWS_39  # Route 53 DNSSEC - no hosted zones in this baseline

  # IAM policy checks - intentional for KMS key policy (needs broad access for key administration)
  - CKV_AWS_109  # IAM policies resource exposure - KMS key policy requires * for key operations
  - CKV_AWS_356  # IAM policies restrictable actions - KMS Encrypt/Decrypt need * resource
  - CKV_AWS_111  # IAM policies write access - KMS admin needs write for key management

  # Permission boundary checks - these ARE the boundaries, they define max permissions
  - CKV_AWS_286  # Privilege escalation in permission boundary - boundary defines allowed scope
  - CKV_AWS_289  # Resource exposure in permission boundary - intentional for boundary definition
  - CKV_AWS_288  # Data exfiltration in permission boundary - s3:GetObject needed for workloads

  # S3 bucket checks - log bucket is destination, can't log to itself
  - CKV_AWS_18   # S3 access logging - log bucket can't log to itself (circular)
  - CKV2_AWS_62  # S3 event notifications - not required for log bucket
  - CKV_AWS_144  # S3 cross-region replication - single region deployment for demo

  # Security group attachment - baseline SG is a template, attached by workloads
  - CKV2_AWS_5   # Security groups attached to resource - baseline SG is reference for workloads

  # Config recorder scope - intentional for cost control in demo
  - CKV2_AWS_45  # Config recorder all resources - scoped to security-relevant resources

  # CloudTrail CloudWatch integration - using S3 + Athena pattern instead
  - CKV2_AWS_10  # CloudTrail CloudWatch Logs - S3 with Athena is alternative pattern

  # GuardDuty org-level - requires AWS Organizations
  - CKV2_AWS_3   # GuardDuty org/region - single account setup, not org-level

# Soft fail for specific frameworks (set to false for blocking)
soft-fail: false

# Compact output
compact: true

# Download external modules
download-external-modules: false
